### ISSUE TITLE
Install guide for Ubuntu 24.04.1

### ISSUE THREAD

**Issue by easytarget** [boosterl/awesome-mango-pi-mq-pro#10]
I think it is worthy of being linked here (I am biased because I wrote it, of course :wink:)

https://github.com/easytarget/MQ-Pro-IO/tree/main

It covers downloading and writing to SD, preconfiguring WiFi, first boot, reconfiguring `flash-kernel` to use the default MQ-Pro device tree and installing bluetooth firmware. It has additional Info on GPIO use and building custom device trees too!

**Comment by boosterl** [comment]
Thanks for the very nice guide! I added it to the Resources section in 35516fb
