### ISSUE TITLE
3D printed case

### ISSUE THREAD

**Issue by MrSVCD** [boosterl/awesome-mango-pi-mq-pro#8]
I found a 3D printed sandwich case for MQ Pro:
https://www.thingiverse.com/thing:5768524
`License
Mango Pi MQ Pro Case (Mango Sandwich)
by avfusion is licensed under the Creative Commons - Public Domain Dedication license.`

**Comment by boosterl** [comment]
Seems like a nice case. Added it to the list, thanks!
