### ISSUE TITLE
armbian link results in 404 page

### ISSUE THREAD

**Issue by Thilosaur** [boosterl/awesome-mango-pi-mq-pro#9]
not sure what to add here, but the armbian link seems to be dead, if anybody knows any good alternative sources for armbian on the mango pi mq pro that would also be nice.

**Comment by boosterl** [comment]
@Thilosaur thanks for pointing this out! Unfortunately Armbian seems to have removed the dedicated page for the MangoPi MQ-Pro. It still available over at [archive.org](https://web.archive.org/web/20240331185447/https://www.armbian.com/mangopi-mq-pro/). The download links there do not seem to work however.

I did find out Armbian maintains an [archive](https://xogium.performanceservers.nl/archive/). There images for the MangoPi MQ-Pro can still be found. How long these will be supported is not clear to me however. I will check the status of this, and hopefully Armbian re-adds a dedicated page for the MangoPi MQ-Pro.
